# Generated by Django 3.2.16 on 2022-12-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notification_extra_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='extra_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
