# Generated by Django 3.2.16 on 2022-12-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_notification_extra_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('approval', 'Approval'), ('added_approver', 'Added_approval')], max_length=20),
        ),
    ]
