# Generated by Django 3.2.16 on 2022-11-19 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0002_projectapprover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapprover',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectapprover',
            name='approval_due_by',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectapprover',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectapprover',
            name='approver_department',
            field=models.CharField(max_length=80),
        ),
    ]
