# Generated by Django 3.2.16 on 2022-11-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_auto_20221119_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapprover',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectapprover',
            name='approval_due_by',
            field=models.DateField(blank=True, null=True),
        ),
    ]
