# Generated by Django 3.2.16 on 2022-11-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approvers',
            field=models.ManyToManyField(to='project_management.UserProfile'),
        ),
    ]
