# Generated by Django 3.2.16 on 2022-11-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectapprover',
            options={},
        ),
        migrations.RemoveField(
            model_name='projectapprover',
            name='project',
        ),
        migrations.AddField(
            model_name='projectapprover',
            name='project',
            field=models.ManyToManyField(to='project_management.Project'),
        ),
    ]
