# Generated by Django 3.2.16 on 2022-11-23 21:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0006_auto_20221123_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='document',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
