# Generated by Django 3.2.16 on 2022-11-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0006_auto_20221121_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectapprover',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='approvers',
            field=models.ManyToManyField(to='project_management.ProjectApprover'),
        ),
    ]
