# Generated by Django 3.2.16 on 2022-11-23 21:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0007_alter_project_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='document',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image'),
        ),
    ]
