# Generated by Django 3.2.16 on 2022-11-28 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0009_remove_project_approvers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approvers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
