# Generated by Django 3.2.16 on 2022-11-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0010_project_approvers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='approvers',
        ),
    ]
