# Generated by Django 3.2.16 on 2022-11-29 09:54

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0011_remove_project_approvers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='document',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='projectapproval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='project_management.userprofile'),
        ),
        migrations.AlterField(
            model_name='projectapproval',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='project_management.project'),
        ),
    ]
