# Generated by Django 3.2.16 on 2022-11-30 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0015_alter_projectapproval_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapproval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to=settings.AUTH_USER_MODEL),
        ),
    ]
