# Generated by Django 3.2.16 on 2022-11-30 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0016_alter_projectapproval_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapproval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='project_management.userprofile'),
        ),
    ]
