# Generated by Django 3.2.16 on 2022-11-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0018_project_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
