# Generated by Django 3.2.16 on 2022-12-04 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0020_remove_projectapproval_approver_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapproval',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
