# Generated by Django 3.2.16 on 2022-12-06 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0025_auto_20221206_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectapproval',
            name='approval_due_by',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
