# Generated by Django 3.2.16 on 2022-12-07 10:53

from django.db import migrations, models
import project_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0028_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateField(validators=[project_management.models.Project.validate_date]),
        ),
        migrations.AlterField(
            model_name='projectapproval',
            name='approval_due_by',
            field=models.DateField(validators=[project_management.models.ProjectApproval.validate_date]),
        ),
    ]
