# Generated by Django 3.2.16 on 2022-12-11 14:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0029_auto_20221207_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='document',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image'),
        ),
    ]
