# Generated by Django 3.2.16 on 2022-12-11 15:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0030_alter_project_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='document',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='document'),
        ),
    ]
